# Generated by Django 4.2.30 on 2026-05-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                ("profile_image", models.ImageField(blank=True, upload_to="profile/images/")),
                ("github_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("resume", models.FileField(blank=True, upload_to="profile/resumes/")),
            ],
        ),
    ]
