# Generated by Django 4.2.30 on 2026-05-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="project_images/")),
                ("url", models.URLField(blank=True)),
                ("is_published", models.BooleanField(default=False)),
                ("publish_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
